import type { Territory, EpistemicCard, TotemicCharacter, PossibleWorldsFuture, TrainStationResource } from './types';

export const MOCK_TERRITORIES: Territory[] = [
  {
    id: 'busyness-park',
    name: 'Busyness Park',
    zone: 'arrivals_departures',
    seek_question: 'What do you believe work is for?',
    tech_tool: 'Employment mapping',
    pipeline: ['inquiry', 'action', 'reflection'],
    tagline: 'Work, value, and the future of employment',
    land_type: 'landscape',
    real_estate_status: 'active',
  },
  {
    id: 'parentown',
    name: 'Parentown',
    zone: 'civic_centre',
    seek_question: 'What do you believe children need most?',
    tech_tool: 'Care mapping',
    pipeline: ['inquiry', 'action', 'reflection'],
    tagline: 'Raising humans, not consumers',
    land_type: 'landscape',
    real_estate_status: 'active',
  },
  {
    id: 'space-agency',
    name: 'Space Agency',
    zone: 'science_fair',
    seek_question: 'What do you owe to the future?',
    tech_tool: 'Futures modelling',
    pipeline: ['inquiry', 'action', 'reflection'],
    tagline: 'Planetary futures and the ethics of scale',
    land_type: 'landscape',
    real_estate_status: 'active',
  },
  {
    id: 'bond-street',
    name: 'Bond Street',
    zone: 'arrivals_departures',
    seek_question: 'What would you not sell?',
    tech_tool: 'Value mapping',
    pipeline: ['inquiry', 'action', 'reflection'],
    tagline: 'Wealth, exchange, and what we risk',
    land_type: 'landscape',
    real_estate_status: 'active',
  },
  {
    id: 'assembly',
    name: 'Assembly',
    zone: 'civic_centre',
    seek_question: 'What makes a claim worth defending publicly?',
    tech_tool: 'Deliberation protocol',
    pipeline: ['inquiry', 'action', 'reflection'],
    tagline: 'The space of reasons',
    land_type: 'landscape',
    real_estate_status: 'active',
  },
  {
    id: 'studio-city',
    name: 'Studio City',
    zone: 'commonwealth',
    seek_question: 'Who owns what you make?',
    tech_tool: 'Authorship mapping',
    pipeline: ['inquiry', 'action', 'reflection'],
    tagline: 'Creativity, authorship, and the politics of making',
    land_type: 'landscape',
    real_estate_status: 'active',
  },
];

function makeAction(desc: string) {
  return {
    id: Math.random().toString(36).slice(2),
    description: desc,
    verification: 'self_reported' as const,
    reward: { train_station_unlock: true, citizenship_points: 10 },
  };
}

export const MOCK_CARDS: Record<string, EpistemicCard[]> = {
  'busyness-park': [
    {
      id: 'bp-1', territory_id: 'busyness-park', position: 1,
      claim: 'Automation will eliminate more jobs than it creates within the next two decades.',
      evidence: [{ source: 'McKinsey Global Institute', url: '#', credibility_score: 85 }],
      possible_worlds_note: 'In worlds where creativity is economically valued, this may be false.',
      challenge_question: 'Name one category of work that automation cannot meaningfully perform.',
      required_action: makeAction('Interview someone whose job has changed due to automation in the past five years.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'bp-2', territory_id: 'busyness-park', position: 2,
      claim: 'A universal basic income is a prerequisite for a humane post-work economy.',
      evidence: [],
      possible_worlds_note: 'In worlds where work is constitutive of identity, UBI alone may be insufficient.',
      challenge_question: 'What social structures would UBI need to preserve in order to be sufficient?',
      required_action: makeAction('Read one critical analysis of UBI from a labour organiser\'s perspective.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'bp-3', territory_id: 'busyness-park', position: 3,
      claim: 'The gig economy redistributes risk from corporations to individuals without redistributing reward.',
      evidence: [],
      possible_worlds_note: 'In a world where gig workers collectively bargain, this relationship could invert.',
      challenge_question: 'Identify a case where gig work genuinely increased a worker\'s autonomy.',
      required_action: makeAction('Map the hidden costs of one gig platform for its workers.'),
      created_by: 'parliament', status: 'published',
    },
  ],
  'assembly': [
    {
      id: 'as-1', territory_id: 'assembly', position: 1,
      claim: 'A democracy that cannot distinguish between opinion and knowledge will collapse into opinion.',
      evidence: [{ source: 'Plato, Republic', url: '#', credibility_score: 70 }],
      possible_worlds_note: 'In worlds with robust epistemic institutions, this collapse can be indefinitely deferred.',
      challenge_question: 'Propose one institutional mechanism for distinguishing knowledge from mere opinion in public deliberation.',
      required_action: makeAction('Attend one public meeting and record how claims are justified.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'as-2', territory_id: 'assembly', position: 2,
      claim: 'Epistemic injustice — the systematic silencing of certain knowers — is a political problem, not merely a social one.',
      evidence: [{ source: 'Miranda Fricker, Epistemic Injustice', url: '#', credibility_score: 88 }],
      possible_worlds_note: 'In worlds with strong individual rights but no collective epistemic norms, this injustice persists.',
      challenge_question: 'Name a domain where knowers are systematically discredited and describe the mechanism.',
      required_action: makeAction('Document one case of epistemic injustice you have witnessed.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'as-3', territory_id: 'assembly', position: 3,
      claim: 'Good deliberation requires not just free speech, but the cultivation of epistemic virtues.',
      evidence: [],
      possible_worlds_note: 'In a world where epistemic virtues are taught, democratic quality improves measurably.',
      challenge_question: 'What is one epistemic virtue that current democratic culture actively discourages?',
      required_action: makeAction('Practice one epistemic virtue deliberately in a conversation this week.'),
      created_by: 'parliament', status: 'published',
    },
  ],
  'parentown': [
    {
      id: 'pt-1', territory_id: 'parentown', position: 1,
      claim: 'Children\'s development is shaped more by peer relationships than by parental instruction.',
      evidence: [{ source: 'Judith Rich Harris, The Nurture Assumption', url: '#', credibility_score: 78 }],
      possible_worlds_note: 'In small, isolated communities, parental influence may dominate.',
      challenge_question: 'Describe a situation where parental values overrode peer influence.',
      required_action: makeAction('Observe and record one peer interaction that shaped a child\'s behaviour.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'pt-2', territory_id: 'parentown', position: 2,
      claim: 'Screens are not inherently harmful to children; the content and context of use determine their effect.',
      evidence: [],
      possible_worlds_note: 'In worlds where screen content is designed for development, this becomes obviously true.',
      challenge_question: 'What conditions would need to hold for screen use to be categorically harmful?',
      required_action: makeAction('Track one week of your household\'s screen use by content type.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'pt-3', territory_id: 'parentown', position: 3,
      claim: 'The nuclear family is a historically recent and culturally specific arrangement, not a natural unit.',
      evidence: [{ source: 'David Graeber, The Dawn of Everything', url: '#', credibility_score: 82 }],
      possible_worlds_note: 'In worlds where extended kinship networks persist, the nuclear family is an aberration.',
      challenge_question: 'What functions does the nuclear family perform that other arrangements struggle to replicate?',
      required_action: makeAction('Interview someone raised in a non-nuclear family structure about its advantages.'),
      created_by: 'parliament', status: 'published',
    },
  ],
  'space-agency': [
    {
      id: 'sa-1', territory_id: 'space-agency', position: 1,
      claim: 'Mars colonisation is a hedge against existential risk, not an escape from terrestrial responsibility.',
      evidence: [],
      possible_worlds_note: 'In worlds where Earth governance fails completely, this framing becomes self-fulfilling.',
      challenge_question: 'At what point does planetary backup become abandonment?',
      required_action: makeAction('Write one paragraph articulating what obligations space-farers owe to those left behind.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'sa-2', territory_id: 'space-agency', position: 2,
      claim: 'Climate change is an epistemic crisis before it is a technological one.',
      evidence: [],
      possible_worlds_note: 'In a world where solutions exist but political will is absent, both crises coexist.',
      challenge_question: 'Identify one piece of evidence that would change your position on this claim.',
      required_action: makeAction('Find one climate scientist\'s account of how denial affects their work.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'sa-3', territory_id: 'space-agency', position: 3,
      claim: 'The Outer Space Treaty of 1967 is inadequate for governing an era of commercial space exploitation.',
      evidence: [{ source: 'UN Office for Outer Space Affairs', url: '#', credibility_score: 90 }],
      possible_worlds_note: 'In a world of one dominant spacefaring nation, the treaty collapses regardless.',
      challenge_question: 'Draft a single principle that should govern resource extraction in space.',
      required_action: makeAction('Research one commercial space mining proposal and identify its governance gaps.'),
      created_by: 'parliament', status: 'published',
    },
  ],
  'bond-street': [
    {
      id: 'bs-1', territory_id: 'bond-street', position: 1,
      claim: 'Markets are social contracts, not natural phenomena — and they can be renegotiated.',
      evidence: [],
      possible_worlds_note: 'In worlds where markets are treated as laws of nature, renegotiation becomes unthinkable.',
      challenge_question: 'Name one market rule that has been successfully changed in your lifetime.',
      required_action: makeAction('Identify one market rule you benefit from that others cannot access.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'bs-2', territory_id: 'bond-street', position: 2,
      claim: 'Compound interest is a mechanism for concentrating wealth, not creating it.',
      evidence: [],
      possible_worlds_note: 'In a world where returns were capped at inflation, this concentration would halt.',
      challenge_question: 'Describe a scenario where compound interest genuinely created rather than transferred value.',
      required_action: makeAction('Calculate what a 5% annual return on £10,000 looks like over 40 years.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'bs-3', territory_id: 'bond-street', position: 3,
      claim: 'Debt is not a personal failure but a structural feature of a money-scarce society.',
      evidence: [],
      possible_worlds_note: 'In a world of full employment and living wages, personal debt would largely disappear.',
      challenge_question: 'Who benefits when personal debt is framed as moral failure?',
      required_action: makeAction('Map the stakeholders in one debt collection industry.'),
      created_by: 'parliament', status: 'published',
    },
  ],
  'studio-city': [
    {
      id: 'sc-1', territory_id: 'studio-city', position: 1,
      claim: 'The death of the author is not the liberation of the reader — it is the ascendancy of the algorithm.',
      evidence: [],
      possible_worlds_note: 'In worlds where algorithmic curation is governed democratically, this is not inevitable.',
      challenge_question: 'Describe a reading practice that resists algorithmic mediation.',
      required_action: makeAction('Spend one week reading only things you discovered without algorithmic recommendation.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'sc-2', territory_id: 'studio-city', position: 2,
      claim: 'Intellectual property law protects the interests of publishers and platforms, not creators.',
      evidence: [],
      possible_worlds_note: 'In a world of creator-controlled distribution, IP law would look completely different.',
      challenge_question: 'Propose one reform to copyright law that would genuinely benefit working artists.',
      required_action: makeAction('Find out how much of the last thing you paid for went directly to its creator.'),
      created_by: 'parliament', status: 'published',
    },
    {
      id: 'sc-3', territory_id: 'studio-city', position: 3,
      claim: 'AI-generated art is not art without a human who takes responsibility for its existence.',
      evidence: [],
      possible_worlds_note: 'In a world where AI systems have legal personhood, this claim may require revision.',
      challenge_question: 'At what point in an AI-assisted creative process does authorship transfer to the human?',
      required_action: makeAction('Create something using AI assistance and write one paragraph about what you authored.'),
      created_by: 'parliament', status: 'published',
    },
  ],
};

export const MOCK_CHARACTER: TotemicCharacter = {
  id: 'char-1',
  user_id: 'user-1',
  name: 'The Wandering Enquirer',
  base_form: 'enquirer',
  attributes: { curiosity: 78, solidarity: 65, rootedness: 55, reach: 82 },
  shaped_by: {
    territories: ['busyness-park', 'assembly'],
    actions_completed: ['bp-1-action', 'as-1-action'],
    citizen_type: 'crowdster',
    waldconsistency_avg: 72,
  },
  visual: {
    silhouette: 'enquirer',
    primary_colour: '#c9940a',
    texture: 'smooth',
    emblem: '🔍',
  },
};

export const MOCK_FUTURES: PossibleWorldsFuture[] = [
  {
    id: 'fut-1',
    author_id: 'user-2',
    title: 'Universal Epistemic Infrastructure',
    description: 'A world in which every school teaches the Waldconsistency framework as a core literacy, alongside reading, writing, and arithmetic.',
    territory_id: 'assembly',
    stakes: [{ user_id: 'user-1', what_they_risk: 'My belief that institutions can self-reform', magnitude: 80 }],
    currency_value: 142.5,
    shares: [{ user_id: 'user-2', share_pct: 60 }, { user_id: 'user-1', share_pct: 40 }],
    options: [{ condition: 'If one country adopts epistemic literacy by 2030', action_if_triggered: 'Double currency value' }],
    arrow_failure_flag: false,
    status: 'open',
  },
  {
    id: 'fut-2',
    author_id: 'user-3',
    title: 'Post-Employment Compact',
    description: 'A social contract in which employment is optional and social contribution is the currency of citizenship.',
    territory_id: 'busyness-park',
    stakes: [{ user_id: 'user-3', what_they_risk: 'My career identity', magnitude: 95 }],
    currency_value: 89.3,
    shares: [{ user_id: 'user-3', share_pct: 100 }],
    options: [],
    arrow_failure_flag: true,
    status: 'open',
  },
];

export const MOCK_RESOURCES: TrainStationResource[] = [
  { id: 'r1', territory_id: 'busyness-park', title: 'The Second Machine Age', type: 'ebook', url: '#', waldconsistency_level: 'K', description: 'Brynjolfsson & McAfee on automation and employment.', is_locked: false },
  { id: 'r2', territory_id: 'busyness-park', title: 'Bullshit Jobs (Graeber)', type: 'ebook', url: '#', waldconsistency_level: 'CR', description: 'A theory of the proliferation of pointless work.', is_locked: false },
  { id: 'r3', territory_id: 'busyness-park', title: '99% Invisible — Future of Work', type: 'audio', url: '#', waldconsistency_level: 'S', description: 'Podcast episode on redesigning labour.', is_locked: true },
  { id: 'r4', territory_id: 'assembly', title: 'Epistemic Injustice (Fricker)', type: 'ebook', url: '#', waldconsistency_level: 'CE', description: 'The foundational text on epistemic injustice.', is_locked: false },
  { id: 'r5', territory_id: 'assembly', title: 'The Enigma of Reason (Mercier & Sperber)', type: 'ebook', url: '#', waldconsistency_level: 'L', description: 'Why humans reason and when they do it well.', is_locked: false },
  { id: 'r6', territory_id: 'assembly', title: 'Philosophy Bites — Deliberative Democracy', type: 'audio', url: '#', waldconsistency_level: 'CN', description: 'Short interview on the theory of deliberative democracy.', is_locked: false },
  { id: 'r7', territory_id: 'space-agency', title: 'The Uninhabitable Earth (Wallace-Wells)', type: 'ebook', url: '#', waldconsistency_level: 'CR', description: 'A detailed account of climate futures.', is_locked: false },
  { id: 'r8', territory_id: 'space-agency', title: 'Lunar — Tim Peake', type: 'ebook', url: '#', waldconsistency_level: 'K', description: 'Astronaut memoir with reflections on planetary scale.', is_locked: true },
  { id: 'r9', territory_id: 'parentown', title: 'The Whole-Brain Child', type: 'ebook', url: '#', waldconsistency_level: 'K', description: 'Neuroscience of child development.', is_locked: false },
  { id: 'r10', territory_id: 'bond-street', title: 'Capital in the 21st Century (Piketty)', type: 'ebook', url: '#', waldconsistency_level: 'CR', description: 'The definitive study of wealth concentration.', is_locked: false },
  { id: 'r11', territory_id: 'studio-city', title: 'Ways of Seeing (Berger)', type: 'video', url: '#', waldconsistency_level: 'CE', description: 'BBC series on image and value in art.', is_locked: false },
  { id: 'r12', territory_id: 'studio-city', title: 'Steal Like an Artist (Kleon)', type: 'ebook', url: '#', waldconsistency_level: 'S', description: 'On creative influence and authorship.', is_locked: false },
];
